name: Star Removal Training (COMPLETELY DISABLED)

# 🚫 WORKFLOW COMPLETAMENTE DISABILITATO
# Non utilizzare GitHub Actions per training - usa solo RunPod
# Questo file è mantenuto solo per riferimento
on: []  # Nessun trigger - workflow completamente disabilitato

jobs:
  # Nessun job - workflow disabilitato
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Disabled
        run: |
          echo "⚠️ Questo workflow è completamente disabilitato"
          echo "🚀 Usa RunPod per il training con GPU reali"
          echo "📖 Leggi RUNPOD_TRAINING_GUIDE.md per istruzioni"
          exit 0
    runs-on: ubuntu-latest
    
    steps:
    - name: ⚠️ TRAINING DISABILITATO SU GITHUB ACTIONS
      run: |
        echo "🚫 TRAINING DISABILITATO!"
        echo "GitHub Actions non ha GPU disponibili per il training."
        echo "Per trainare il modello, usa RunPod con GPU H100/H200:"
        echo ""
        echo "1. Vai su https://runpod.io"
        echo "2. Crea un pod con GPU (H100/H200/RTX4090)"
        echo "3. Segui la guida in RUNPOD_TRAINING_GUIDE.md"
        echo ""
        echo "Comando rapido per RunPod:"
        echo "git clone https://github.com/SyqonCollective/xstar.git && cd xstar && python main.py train --epochs 100 --batch-size 16 --image-size 768 768"
        exit 0
        
  # ⚠️ STEPS RIMOSSI - Usa RunPod per training reale con GPU
  # Tutti gli altri step sono stati disabilitati perché GitHub Actions non ha GPU
        retention-days: 30
    
    - name: Upload tensorboard logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: tensorboard-logs
        path: outputs/**/tensorboard/
        retention-days: 7

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest test_*.py -v || echo "No pytest found, running manual tests"
        python test_gpu.py
    
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
